---
- name: Local actions for all hosts
  hosts: all
  become: no
  gather_facts: no
  tasks:
        - name: Remove stale entries from known_hosts file
          local_action: command ssh-keygen -R {{ inventory_hostname }}
- name: Local actions for localhost
  hosts: 127.0.0.1
  connection: local
  become: no
  tasks:
        - name: Save terraform variables to a file
            shell: terraform output |tr '=' ':' > ../Ansible/group_vars/all/terraform_outputs.var 
            args: 
              chdir: ../Terraform
        - name: Add DNS internal domain to terraform vars
            shell: (echo -n 'aws_internal_domain:'; echo -n ' '; terraform output master01_name|cut -d. -f2-) >> ../Ansible/group_vars/all/terraform_outputs.var 
            args: 
              chdir: ../Terraform
        - name: Load terraform output variables
          include_vars:
            file: group_vars/all/terraform_outputs.var
        - name: Render ssh jinja2 template
          template:
            src: ssh.cfg.j2
            dest: ssh.cfg
            mode: 0644

- name: Assing a FQDN name to the bastion
  hosts: bastion
  tasks:
        - name: Assign a proper hostname to the server
          hostname:
              name: "{{ inventory_hostname }}"

- name: Prerequisites for OCP cluster members
  hosts: all
  tasks:
        - name: Find repo files
          find:
            paths: /etc/yum.repos.d
            patterns: '*.repo'
          register: repo_files
        - name: Disable rhui repositories
          command: mv {{ item.path }} {{ item.path }}.disabled
          when: "'rhui' in item.path"
          with_items: "{{ repo_files.files }}"
        - name: Register server with Red Hat
          redhat_subscription:
              state: present
              username: "{{ subscription_username }}"
              password: "{{ subscription_password }}"
              pool_ids: 8a85f9833e1404a9013e3cddf99305e6
        - name: Enable the required repositories for Openshift
          rhsm_repository:
              name: 
                - rhel-7-server-rpms
                - rhel-7-server-extras-rpms
                - rhel-7-server-ose-3.11-rpms
                - rhel-7-fast-datapath-rpms
                - rhel-7-server-ansible-2.6-rpms
              purge: True
        - name: Install base packages
          yum:
              state: latest
              name:
                - openshift-ansible
                - vim
                - screen 
        - name: Update system packages
          yum:
              state: latest
              name: '*'
          when: update_packages
...
